# This is a basic workflow to help you get started with Actions

name: Run arxiv-reader on Arxiv paper

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      arxiv_id:
        description: 'Arxiv ID of the paper to run arxiv-reader on'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Run arxiv-reader
        run: cd arxiv-reader && python convert.py "${{ github.event.inputs.arxiv_id }}"
      - name: Upload arxiv-reader output
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.inputs.arxiv_id }}.wav"
          path: "arxiv-reader/${{ github.event.inputs.arxiv_id }}.wav"